name: Keep Supabase Alive Notas Web

on:
  schedule:
    # Se ejecuta cada 3 días a las 00:00 UTC
   - cron: '0 0 */5 * *' # Se ejecuta a las 00:00 cada 5 días
  workflow_dispatch: # Permite ejecutarlo manualmente para probar

jobs:
  ping_db:
    runs-on: ubuntu-latest
    steps:
      - name: Install psql
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Ping Supabase Database
        env:
          DB_URL: ${{ secrets.SUPABASE_DB_URL }}
        run: |
          psql "$DB_URL" -c "SELECT 1;"
